game_manager:
  max_has_work: 5
  init_y_m_red: 1.7
  INIT_Z_m: 0.205
  WORK_HEIGHT_m: 0.087

ros_cmd:
  velocity_limit_scale: 1
  KT_OUT: 0.08
  work_mass: 0.06
  # acceleration_limit_scale: 1
  # current_max_A: 8
pulley:
  pitch: 0.002
  teeth: 54 

show_for_rviz:
  joint_names: ["arm/joint1","arm/joint2","arm/joint3","gripper/joint1"]

radius2meter:
  world_frame: "world"
  
  world_position_topic: "pose_stamped"
